# Generated by Django 3.2.9 on 2021-11-13 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hear', models.CharField(max_length=500)),
                ('engage', models.CharField(max_length=500)),
                ('apply', models.CharField(max_length=500)),
                ('respond', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('refrence', models.CharField(max_length=20)),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblejournalapi.reader')),
            ],
        ),
    ]
